settings:
  title: 'Discretize Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: discretize-eu-mainsite # unique identifier
    name: discretize.eu
    description: 'Main website' # default=empty
    url: 'https://discretize.eu' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: discretize-eu-newsite # unique identifier
    name: discretize.pages.dev
    description: 'New website' # default=empty
    url: 'https://discretize.pages.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: discretize-docs # unique identifier
    name: discretize-docs.pages.dev
    description: 'Docs website' # default=empty
    url: 'https://discretize-docs.pages.dev' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: discretize-optimizer # unique identifier
    name: optimizer.discretize.eu
    description: 'Gear Optimizer' # default=empty
    url: 'https://optimizer.discretize.eu' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
  - id: cms-auth # unique identifier
    name: discretize-cms-auth
    description: 'Auth Proxy for the cms' # default=empty
    url: 'https://auth.princeps.biz' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true




